---
# Deployment descriptor
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: "sandbox"
    app.kubernetes.io/component: "sandbox"
    app.kubernetes.io/part-of: "sandbox"
    app.kubernetes.io/instance: "sandbox-main"
    app.kubernetes.io/version: "1.0.0"
  name: "sandbox"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "sandbox"
      app.kubernetes.io/component: "sandbox"
      app.kubernetes.io/part-of: "sandbox"
      app.kubernetes.io/instance: "sandbox-main"
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      annotations:
        k8s.grafana.com/scrape: "true"
      labels:
        app.kubernetes.io/name: "sandbox"
        app.kubernetes.io/component: "sandbox"
        app.kubernetes.io/part-of: "sandbox"
        app.kubernetes.io/instance: "sandbox-main"
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: sandbox
        image: "alainpham/sandbox:1.0.0"
        imagePullPolicy: "Always"
        command: ["tail", "-f", "/dev/null"]
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
        ports:
        volumeMounts:
      volumes:
---