apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: camel-pod-monitor
spec:
  selector:
    matchLabels:
      tech: 'apache-camel'
  namespaceSelector:
    matchNames:
      - TARGET_NAMESPACE
  podMetricsEndpoints:
  - path: /metrics
    port: prometheus
    interval: 15s
    relabelings:
    - separator: ;
      regex: __meta_kubernetes_pod_label_(.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_pod_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace
    