{
 "title": "Camel Quarkus Dashboard - Context View (micrometer)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{eventType=\"RouteEvent\"},namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{eventType=\"RouteEvent\",namespace=\"$namespace\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(CamelExchangesSucceeded_total{namespace=\"$namespace\",camelContext=\"$context\"},routeId)"
    }
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": {
     "query": "label_values(CamelMessageHistory_seconds_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"},nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of parallel instances of this camel context running ",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (CamelRoutesRunning_routes{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(CamelRoutesRunning_routes{namespace=\"$namespace\",camelContext=\"$context\"}) / sum(CamelRoutesAdded_routes{namespace=\"$namespace\",camelContext=\"$context\"})*100",
     "legendFormat": "Running"
    },
    {
     "expr": "max(CamelRoutesAdded_routes{namespace=\"$namespace\",camelContext=\"$context\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (increase(CamelExchangesFailed_total{namespace=\"$namespace\",camelContext=\"$context\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (camelContext) (increase(CamelExchangesFailed_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (camelContext) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exchanges Inflight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(CamelExchangesInflight{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Pods Per Node Distribution",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (node_name) (CamelRoutesRunning_routes{namespace=\"$namespace\",camelContext=\"$context\"})\n"
    }
   ]
  },
  {
   "title": "Traffic Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "stat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 6 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (camelContext) (irate(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 6 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (irate(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route Failure % - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 6 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (routeId) (increase(CamelExchangesFailed_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (routeId) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "stat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 6 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (CamelExchangesInflight{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (CamelExchangesInflight{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Execution Times Per Route Since Start",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "stat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}) / sum by (route) (CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 12 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}) / sum by (route) (CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 12 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}) / sum by (route,kubernetes_pod_name) (CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 12 },
   "repeat": "route",
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (avg by (processor) (org_apache_camel_LastProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Execution Times Per Route Over Last 30 sec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Exec time $route",
     "type": "stat",
     "description": "Average execution time for a route",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (route) (increase(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])) / sum by (route) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s]))"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - all instances",
     "type": "graph",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 13 },
     "repeat": "route",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (route) (increase(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])) / sum by (route) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])))"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - per instances",
     "type": "graph",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 13 },
     "repeat": "route",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (route,kubernetes_pod_name) (increase(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])) / sum by (route,kubernetes_pod_name) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Processor Execution Times - $route",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 13 },
     "repeat": "route",
     "targets": [
      {
       "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (increase(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}[30s])) / sum by (processor) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}[30s])))"
      },
      {
       "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (increase(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}[30s])))"
      },
      {
       "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",camelContext=\"$context\",routeId=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (increase(CamelExchangesTotal_total{namespace=\"$namespace\",camelContext=\"$context\",type=\"processors\",processor=~\"$processor\"}[30s])))"
      }
     ]
    }
   ]
  }
 ]
}