{
 "title": "Artemis Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(artemis_connection_count,kubernetes_namespace)"
   },
   {
    "name": "brokercluster",
    "label": "Broker Cluster",
    "query": "label_values(artemis_connection_count{kubernetes_namespace=\"$namespace\"},broker)"
   },
   {
    "name": "brokerinstance",
    "label": "Broker Instance",
    "query": "label_values(artemis_connection_count{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\"},statefulset_kubernetes_io_pod_name)"
   },
   {
    "name": "address",
    "label": "Address",
    "query": "label_values(artemis_message_count{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\"},address)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Address Memory Usage $brokerinstance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "brokerinstance",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_address_memory_usage_percentage{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\"}"
    }
   ]
  },
  {
   "title": "Diskstore Usage $brokerinstance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "repeat": "brokerinstance",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_disk_store_usage{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\"}"
    }
   ]
  },
  { "title": "Broker Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (artemis_message_count{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Address Summary",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "sum by (address) (artemis_messages_added{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"})",
     "legendFormat": "Added"
    },
    {
     "expr": "sum by (address) (artemis_messages_acknowledged{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"})",
     "legendFormat": "Acks"
    },
    {
     "expr": "sum by (address) (artemis_messages_expired{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum by (address) (artemis_messages_killed{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"})",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "Messages added/sec over last 30sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (irate(artemis_messages_added{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"}[30s]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages acknowledged/sec over last 30sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (irate(artemis_messages_acknowledged{kubernetes_namespace=\"$namespace\",broker=~\"$brokercluster\",statefulset_kubernetes_io_pod_name=~\"$brokerinstance\",address=~\"$address\"}[30s]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}