global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "camel-quarkus-dev"
    metrics_path: /q/metrics
    relabel_configs:
      - target_label: app_kubernetes_io_part_of
        replacement: smoke-test-app-quarkus
      - target_label: app_kubernetes_io_name
        replacement: smoke-test-app-quarkus
      - target_label: app_kubernetes_io_component
        replacement: smoke-test-app-quarkus
      - target_label: app_kubernetes_io_instance
        replacement: smoke-test-app-quarkus-master
      - target_label: app_kubernetes_io_version
        replacement: "2.0.0"
      - target_label: cluster
        replacement: cloud
      - target_label: node
        replacement: worker-01
      - target_label: pod
        replacement: smoke-test-app-quarkus-1
      - target_label: namespace
        replacement: camel-ns
    static_configs:
      - targets:
          - "smoke-test-app-quarkus:8080"